airdrop/urls.py
from django.contrib import admin
from django.urls import path, include
from airdrop import settings
from django.conf.urls.static import static

admin.site.site_header = 'SHAREME'
admin.site.index_title = 'Admin'
admin.site.site_title = 'Book Share'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls', namespace='bot')),
    path('user/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bot/urls.py
from . import views
from django.urls import path

app_name = 'bot'

urlpatterns = [

    path(
        '',
        views.book_list,
        name='book-list'
    ),

    path(
        'category/<slug:category_slug>/',
        views.book_list,
        name='book-list-by-category'
    ),

    path(
        'author/<slug:author>/',
        views.book_list,
        name='books-by-author-name'),

    path(
        'book/<int:id>/view-book-detail/',
        views.book_detail,
        name='book-detail'),

    path(
        'share/<int:id>/share-book/',
        views.share_book,
        name='share-book'
    ),

    path(
        'dashboard/',
        views.dashboard,
        name='dashboard'
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.user_register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.user_profile, name="profile"),
    path('book/create_book/', views.create_book, name='create-book'),
]

bot/models.py
from django.utils.text import slugify
from django.urls import reverse
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255)
    date_birth = models.DateField()
    nationality = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('bot:books-by-author-name', kwargs={"author": self.slug})


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("bot:book-list-by-category", args=[self.slug])


class Book(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    description = models.TextField()
    image = models.ImageField(upload_to='books', default='book.jpg')
    slug = models.SlugField(max_length=100)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='books')
    authors = models.ManyToManyField(Author, related_name='books')
    isbin = models.CharField(max_length=100, null=True, blank=True)
    available = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("bot:book-detail", args=[self.id])

bot/forms.py
from django import forms
from .models import Book
from django.forms import ModelForm


class BookForm(ModelForm):

    class Meta:
        model = Book
        fields = ['name', 'price', 'description', 'image', 'category', 'isbin']

        widgets = {
            'description': forms.Textarea(attrs={"cols": 10, "rows": 5}),
            'name': forms.TextInput(attrs={'class': 'p-2 fw-bolder'}),
            'category': forms.SelectMultiple(attrs={'class': 'form-select p-2 form-select-sm '})
        }


class EmailBookForm(forms.Form):
    name = forms.CharField(
        max_length=64,
        min_length=5,
        disabled=True,
        label='YOUR NAME',
        widget=forms.TextInput(
            attrs={'class': 'fw-bold p-3 form-control text-dark'}
        )
    )

    to = forms.EmailField(
        required=True,
        max_length=100,
        min_length=10,
        label='RECIPIENT-EMAIL',
        help_text="Enter your email here...",
        widget=forms.TextInput(attrs={
            'class': 'fw-bolder p-3 form-control'
        })
    )

    comment = forms.CharField(
        label="COMMENT",
        help_text='What do you think of the book?',
        required=True,
        widget=forms.Textarea(attrs={
            "cols": 10,
            "rows": 5,
            'class': 'fw-medium p-3 form-control'
        })
    )

bot/views.py
from audioop import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpRequest
from django.contrib import messages
from .models import Book, Category, Author
from .forms import BookForm, EmailBookForm
from airdrop.settings import EMAIL_HOST_USER, MESSAGE_EMAIL


def book_list(request: HttpRequest, category_slug=None, author=None):
    # Fetch all authors and categories for filtering options
    authors = Author.objects.all()
    categories = Category.objects.all()

    # Initialize the queryset for books
    books = Book.objects.filter(available=True)

    # Filter by category if category_slug is provided
    category = None
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        books = books.filter(category=category)

    # Filter by author if author is provided
    author = None
    if author:
        author = get_object_or_404(Author, slug=author)
        books = books.filter(authors=author)

    # Render the book list template with the filtered data
    return render(
        request,
        'bot/book-list.html',
        context={
            'books': books,
            'category': category,
            'categories': categories,
            'author': author,
            'authors': authors
        }
    )


def book_detail(request: HttpRequest, id):
    book = get_object_or_404(Book, pk=id)
    return render(request, 'bot/book-detail.html', context={'book': book, 'form': EmailBookForm(initial={'name': request.user.username})})


@login_required
def create_book(request: HttpRequest):
    if request.method == "POST":
        form = BookForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f"Book '{
                             form.cleaned_data['name']}' created successfully!")
            return redirect('bot:create-book')
        else:
            return render(request, 'bot/create-book.html', context={'form', form})
    form = BookForm()
    return render(request, 'bot/create-book.html', context={"form": form})


@login_required(login_url='users:login')
def share_book(request: HttpRequest, id):

    # Retrieve a book from the database
    book = get_object_or_404(Book, pk=id)

    if request.method == "POST":
        form = EmailBookForm(request.POST)

        if form.is_valid():
            # Create book url for sending....
            book_url = request.build_absolute_uri(
                book.get_absolute_url()
            )

            # Get form data..........
            name = form.cleaned_data.get('name')
            to = form.cleaned_data.get('to')
            comment = form.cleaned_data.get('comment')

            # Compose an email
            subject = f"{name} recommended you a book {book.name}"
            message = MESSAGE_EMAIL.replace('BUYER', name).replace(
                'URL', book_url).replace('COMMENT', comment).replace("NAME", book.name)

            # Send email.........
            send_mail(subject, message, EMAIL_HOST_USER, [to])

            # Send a success message
            messages.success(request, f'Email sent to {name}')
            return redirect(reverse('bot:book-list'))
        return render(request, 'bot/book-detail.html', context={'form': form})
    return render(request, 'bot/book-detail.html', context={'form': EmailBookForm()})


def dashboard(request: HttpRequest):
    return render(request, 'bot/dashboard.html')

bot/templates/bot/base.html
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'bot/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'bot/css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'bot/css/custom.css' %}" />
  <title>{% block title %} Home {% endblock %}</title>
</head>

<body class="bg-secondary-subtle ">
  <!-- Navigation bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary ">
    <div class="container-fluid">

      <a class="navbar-brand text-info fw-bold fw-bold text-decoration-none" href="{% url 'bot:book-list' %}">
        ShareMe
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navdrop">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navdrop">
        <ul class="navbar-nav p-3">
          <li class="nav-item">
            <a href="{% url 'bot:dashboard' %}" class="nav-link text-info  fw-bold ">Dashboard</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'users:logout' %}" class="nav-link text-info  fw-bold ">Logout</a>
          </li>

          <li class="nav-item">
            <a href="{% url 'users:profile' %}" class="nav-link text-info  fw-bold">Profile</a>
          </li>
          {% else %}

          <li class="nav-item">
            <a href="{% url 'users:login' %}" class="nav-link text-info  fw-bold ">Login</a>
          </li>

          <li class="nav-item">
            <a href="{% url 'users:register' %}" class="nav-link text-info  fw-bold ">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Application Messages-->
  {% include 'bot/messages.html' %}

  <!-- Main Content -->
  <main>
    {% block content %} {% endblock content %}
  </main>

  <!-- Footer -->
  <footer>
    {% block footer %} {% endblock footer %}
  </footer>
  <script src="{% static 'bot/js/custom.js' %}"></script>
  <script src="{% static 'bot/js/bootstrap.js' %}"></script>
  <script>
    feather.replace()
  </script>
</body>

</html>

bot/templates/bot/book-detail.html
{% extends 'bot/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Book {% endblock %}

{% block content %}
<div class="container-fluid mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 col-xl-10 p-4">
      <div class="row">
        <div class="col-md-4">
          <div class="card shadow border-0">
            <img src="{{ book.image.url }}" alt="{{ book.name }}" class="card-img-top img-fluid"
              style="width:100%; height:auto">
          </div>
        </div>
        <div class="col-md-8 d-flex flex-column justify-content-center">
          <h3 class="text-dark">{{ book.name }}</h3>
          <p class="lead">$ {{ book.price }}</p>
          <p class="lead">{{ book.description }}</p>
          <div class="mt-3">
            <button type="button" class="btn btn-info text-light my-3 w-25 fw-bolder " data-bs-toggle="modal"
              data-bs-target="#updateinfo">Share BOOK
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Share Modal -->
<div class="modal fade" id="updateinfo">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-secondary-subtle  border-0 ">
        <h5 class="modal-title text-info fw-bold ms-5">{{ book.name }}</h5>
        <button type="button" class="btn-close " data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <form action="{% url 'bot:share-book' book.id %}" method='POST' novalidate aut>
          {% csrf_token %}
          {{ form|crispy}}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-info text-light fw-bold ">Share</button>
        <button type="button" class="btn btn-danger text-light fw-bold " data-bs-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

bot/templates/bot/book-list.html
{% extends 'bot/base.html' %}

{% block title %} Books {% endblock %}

{% block content %}
<div class="container-fluid mt-5">
  <div class="row g-5 p-3">
    <div class="col-md-3">
      <div class="card shadow border-0 h-100 bg-secondary rounded-4">
        <div class="card-body">
          <h4 class="p-2 text-light fw-semibold ">Books Categories</h4>
          <hr>
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'bot:book-list' %}" {%if not category%}
                class="text-warning  fw-bold p-3 text-decoration-none" {%endif%}
                class="text-light fw-bolder p-2 text-decoration-none m-2 ">All</a>
              <hr>
            </li>
            {%for category in categories%}
            <li>
              <h5>
                <a href="{{ category.get_absolute_url }}" class="text-decoration-none text-info fw-bolder p-2">
                  {{ category.name }}
                </a>
              </h5>
            </li>
            <hr class="text-bark">
            {% endfor %}
          </ul>

          <!-- Search pattern for Book Author -->
          <h4 class="p-2 text-light fw-bold">Get Books For</h4>
          <hr>
          <ul class="list-unstyled">
            {% for author in authors %}
            <li>
              <h5>
                <a href="{{ author.get_absolute_url }}" class="text-decoration-none text-info   fw-bolder p-2">
                  {{ author.name }}
                </a>
              </h5>
            </li>
            <hr class="text-bark">
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <h5 class="text-success  p-2 m-2 fw-bolder ">
        {%if category%} Books for {{category.name|title}} {%else%} {{books|length}} Books found{%endif%}
      </h5>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4 g-4">
        {% for book in books %}
        <div class="col">
          <div class="card h-100 shadow-sm rounded-4">
            <a href="{{ book.get_absolute_url }}" class="text-decoration-none">
              <img src="{{ book.image.url }}" class="card-img-top" alt="{{ book.name }}"
                style="height: 500px; object-fit: cover;">
            </a>
            <div class="card-body d-flex flex-column bg-secondary">
              <a href="{{ book.get_absolute_url }}" class="text-decoration-none">
                <h3 class="card-title text-info mt-3">{{ book.name }}</h3>
              </a>
              <h5 class="card-text mb-2 lead fw-bolder text-warning ">$ {{ book.price }}</h5>
              <h5 class="card-text lead fw-bolder text-info ">{{ book.description }}</h5>
            </div>
          </div>
        </div>
        {% empty %}
        <div class="container-fluid  bg-body-tertiary h-25 text-center mt-5">
          <p class="lead text-center p-3 m-3 "> Sorry no results found for category "{{ category.name }}" </p>
        </div>
        {% endfor %}
      </div>
      <div class="mt-4">
        {% include "bot/pagination.html" with page=books %}
      </div>
    </div>
  </div>
</div>
{% include 'bot/footer.html' %}
{% endblock content %}

bot/templates/bot/dashboard.html
{% extends 'bot/base.html' %}

{% block title %} Book {% endblock %}

{% block content %}
<!-- Start -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Dashboard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <img src="/media/default.png" class="rounded-circle" alt="Profile Picture" style="width: 60; height: 60;">
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Contents sidebar -->
<div class="container-fluid">
  <div class="row">
    <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">
              <span data-feather="home"></span>
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Page 1
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Page 2
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Page 3
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Page 4
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Page 5
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>
      <!-- Main content goes here -->
      <!-- <p class="lead p-3 m-2 text-center fw-bolder text-secondary"> copyright @ {% now "Y" %}
        <a href="/" class="text-info text-decoration-none"> mlindatech.com</a> -->
      </p>
    </main>
  </div>
</div>
<!-- end -->
{% endblock %}

bot/templates/bot/footer.html
<!-- Footer -->
<div class="container-fluid bg-black mt-5 pb-2">
  <div class="row">
    <div class="col-3">
      <h5 class="text-info  text-center mt-3">Contributors</h5>
      <p class="text-light lead mt-3 p-3">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium, quod
        atque, similique reprehenderit
        obcaecati sint repellendus iste a facere, dolores assumenda sunt corrupti temporibus error molestiae.
        Provident possimus unde adipisci!</p>
    </div>
    <div class="col-3">
      <h5 class="m-2 text-center text-info mt-3">About</h5>
      <p class="text-light lead mt-3 p-3">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium, quod
        atque, similique reprehenderit
        obcaecati sint repellendus iste a facere, dolores assumenda sunt corrupti temporibus error molestiae.
        Provident possimus unde adipisci!</p>
    </div>
    <div class="col-3">
      <h5 class="text-info  m-2 text-center mt-3">Campany</h5>
      <p class="text-light lead mt-3 p-3">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium, quod
        atque, similique reprehenderit
        obcaecati sint repellendus iste a facere, dolores assumenda sunt corrupti temporibus error molestiae.
        Provident possimus unde adipisci!</p>
    </div>
    <div class="col-3">
      <h5 class="text-info  m-2 text-center mt-3">Policy</h5>
      <p class="text-light lead mt-3 p-3">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium, quod
        atque, similique reprehenderit
        obcaecati sint repellendus iste a facere, dolores assumenda sunt corrupti temporibus error molestiae.
        Provident possimus unde adipisci!!</p>
    </div>
  </div>
  <p class="text-light text-center mt-5 mb-5 p-5">@ Copyright {% now "Y" %} by
    <a href="/" class="text-decoration-none  fw-bold p-2 text-info">ShareMe.Inc
    </a>
  </p>
</div>

bot/templates/bot/messages.html
{% if messages %}
{% for message in messages %}
<div class="conteiner-fluid alert alert-{{message.tags}} p-2 text-center text-success fw-bold lead">
  {{message}}
</div>
{% endfor %}
{% endif %}

bot/templates/bot/pagination.html
<div class="container justify-content-center align-items-center mt-5 d-none ">
  <span>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" class="btn btn-info btn-sm p-2 text-light fw-bold">Previous</a>
    {% endif %}

    <span class="text-secondary fw-bold p-2">
      Page {{ page.number}} of {{ page.paginator.num_pages }}
    </span>

    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="btn btn-info btn-sm p-2 text-light
    fw-bold">
      Next
    </a>
    {% endif %}
  </span>
</div>